# Generated by Django 5.0.3 on 2024-04-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="astronomyshow",
            name="show_theme",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="showsession",
            name="astronomy_show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show_sessions",
                to="product.astronomyshow",
            ),
        ),
        migrations.AlterField(
            model_name="showsession",
            name="planetarium_dome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show_sessions",
                to="product.planetariumdome",
            ),
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(to="product.showtheme"),
        ),
    ]
