# Generated by Django 5.0.3 on 2024-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showtheme",
            options={},
        ),
        migrations.RenameField(
            model_name="astronomyshow",
            old_name="show_theme",
            new_name="show_themes",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "show_session"),
                name="unique_ticket_row_seat_show_session",
            ),
        ),
    ]
